### ISSUE TITLE
Invalid JSON in profile windows-11--firefox-128-0

### ISSUE THREAD

**Issue by dleber** [ulixee/browser-profile-data#1]
FYI this profile has invalid JSON:

https://github.com/ulixee/browser-profile-data/blob/a64cb50bd037176ee9c267a5779e6235ce8afb31/profiles/windows-11--firefox-128-0/http-xhr.json#L6317

This is the only profile that had this issue.

**Comment by blakebyrnes** [comment]
Thanks!
